### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by julzmon** [components-ai/issues#4] opened 2021-08-17 19:38 UTC
https://components.ai/theme/v86uC11OB815iEOzMVS5

While I was adjusting colors something broke.

```

Some cookies are misusing the recommended “SameSite“ attribute 5
Array [ {…} ]
home-79951b7f4f7bbd0192f7.js:1:28769
TypeError: n.hslObject is undefined
    NextJS 70
framework-5befd6a844e6007443d6.js:1:83586
TypeError: n.hslObject is undefined
    NextJS 70
main-13a810625311e659e50b.js:1:8378
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred main-13a810625311e659e50b.js:1:8395
    NextJS 70

​

```

**Comment by johno** [comment] 2021-08-18 14:18
Thanks for reporting! We've deployed a fix, so going to close this now. Let us know if you encounter anything else 🙏 

## What broke?

In our code we calculate accessible color combinations that you can see in the settings panel. In a recent code update we introduced a regression that allowed system colors (like inherit, currentcolor, etc) into that calculation. That caused an error since we can't use those to properly calculate a contrast ratio.

## What are we doing to avoid this in the future?

We'll be adding a few unit tests for color combination calculations to ensure that system colors and those with alpha channels less than 1 are filtered out.

**Closed as completed by johno** 2021-08-18 14:18 UTC
